### ISSUE TITLE
Request for the pre-trained model on the DFaust

### ISSUE THREAD

**Issue by bearprin** [Chumbyte/DiGS#2]
Hi, 

thanks for your work; it is impressive and creative. More importantly, your elegant code helps the step of the community.

I would like to ask for a favor from you. Could you release the pre-trained model trained on the DFasut dataset, please?

The training time is too long on my machine. I do not have enough resources to handle that.

Looking forward to your reply!

**Comment by Chumbyte** [comment]
I think you emailed and I sent the pre-trained model to you, but just in case (or for others): [https://drive.google.com/file/d/1IdZAlv5qpzKle7cErfNEp_IUjNR6UOIk/view?usp=share_link](https://drive.google.com/file/d/1IdZAlv5qpzKle7cErfNEp_IUjNR6UOIk/view?usp=share_link) .
I don't think we explored as much as we could, we barely had the resources to run it as well back then (and it took us a week of training).
